import CitationManager from './CitationManager.vue';
import {getSubmissionMock} from '@/mockFactories/submissionMock';
import {getPublicationMock} from '@/mockFactories/publicationMock';

export default {
	title: 'Managers/CitationManager',
	component: CitationManager,
	render: (args) => ({
		components: {CitationManager},
		setup() {
			return {args};
		},
		template: `<CitationManager v-bind="args"/>`,
	}),
};

export const Base = {
	args: {
		submission: getSubmissionMock(),
		publication: getPublicationMock({
			citationsMetadataLookup: true,
			citations: [
				{
					_href:
						'http://localhost:7002/index.php/publicknowledge/api/v1/citations/285',
					arxiv: null,
					authors: [
						{
							givenName: 'Lutz',
							familyName: 'Bornmann',
							orcid: 'https://orcid.org/0000-0003-0810-7091',
							openAlex: 'https://openalex.org/A5027052270',
						},
						{
							givenName: 'Robin',
							familyName: 'Haunschild',
							orcid: 'https://orcid.org/0000-0001-7025-7256',
							openAlex: 'https://openalex.org/A5004115158',
						},
						{
							givenName: 'Kevin W.',
							familyName: 'Boyack',
							orcid: 'https://orcid.org/0000-0001-7814-8951',
							openAlex: 'https://openalex.org/A5031368885',
						},
						{
							givenName: 'Werner',
							familyName: 'Marx',
							orcid: 'https://orcid.org/0000-0002-1763-5753',
							openAlex: 'https://openalex.org/A5010206618',
						},
						{
							givenName: 'Jan C.',
							familyName: 'Minx',
							orcid: 'https://orcid.org/0000-0002-2862-0178',
							openAlex: 'https://openalex.org/A5060648323',
						},
					],
					date: '2022-09-22',
					doi: '10.1371/journal.pone.0274693',
					firstPage: 'e0274693',
					handle: null,
					id: 285,
					isProcessed: true,
					isStructured: true,
					issue: '9',
					lastPage: 'e0274693',
					openAlex: 'https://openalex.org/W4296793747',
					publicationId: 17,
					rawCitation:
						'How relevant is climate change research for climate change policy? An empirical analysis based on Overton. DOI: 10.1371/journal.pone.0274693',
					rawCitationWithLinks:
						'How relevant is climate change research for climate change policy? An empirical analysis based on Overton. DOI: 10.1371/journal.pone.0274693',
					seq: 1,
					sourceHost: 'Public Library of Science',
					sourceIssn: '1932-6203',
					sourceName: 'PLoS ONE',
					sourceType: 'journal',
					title:
						'How relevant is climate change research for climate change policy? An empirical analysis based on Overton data',
					type: 'journal-article',
					url: null,
					urn: null,
					volume: '17',
					wikidata: null,
				},
				{
					_href:
						'http://localhost:7002/index.php/publicknowledge/api/v1/citations/286',
					arxiv: null,
					authors: [
						{
							givenName: 'Andreas',
							familyName: 'Jangmo',
							orcid: 'https://orcid.org/0000-0001-6928-4791',
							openAlex: 'https://openalex.org/A5059929914',
						},
						{
							givenName: 'Ralf',
							familyName: 'Kuja\u2010Halkola',
							orcid: 'https://orcid.org/0000-0002-3765-2067',
							openAlex: 'https://openalex.org/A5052670662',
						},
						{
							givenName: 'Ana',
							familyName: 'P\u00e9rez-Vigil',
							orcid: 'https://orcid.org/0000-0002-5059-6426',
							openAlex: 'https://openalex.org/A5069503434',
						},
						{
							givenName: 'Catarina',
							familyName: 'Almqvist',
							orcid: 'https://orcid.org/0000-0002-1045-1898',
							openAlex: 'https://openalex.org/A5051409156',
						},
						{
							givenName: 'Cynthia M.',
							familyName: 'Bulik',
							orcid: 'https://orcid.org/0000-0001-7772-3264',
							openAlex: 'https://openalex.org/A5003258692',
						},
						{
							givenName: 'Brian M.',
							familyName: 'D\u2019Onofrio',
							orcid: 'https://orcid.org/0000-0002-5248-7434',
							openAlex: 'https://openalex.org/A5083088232',
						},
						{
							givenName: 'Paul',
							familyName: 'Lichtenstein',
							orcid: 'https://orcid.org/0000-0003-3037-5287',
							openAlex: 'https://openalex.org/A5046450925',
						},
						{
							givenName: 'Ewa',
							familyName: 'Ahnemark',
							orcid: 'https://orcid.org/0000-0002-1801-9506',
							openAlex: 'https://openalex.org/A5077844857',
						},
						{
							givenName: 'Tamara',
							familyName: 'Werner\u2010Kiechle',
							orcid: 'https://orcid.org/0000-0001-9145-3790',
							openAlex: 'https://openalex.org/A5013137279',
						},
						{
							givenName: 'Henrik',
							familyName: 'Larsson',
							orcid: 'https://orcid.org/0000-0002-6851-3297',
							openAlex: 'https://openalex.org/A5021664662',
						},
					],
					date: '2021-03-17',
					doi: '10.1371/journal.pone.0247724',
					firstPage: 'e0247724',
					handle: null,
					id: 286,
					isProcessed: true,
					isStructured: true,
					issue: '3',
					lastPage: 'e0247724',
					openAlex: 'https://openalex.org/W3138005625',
					publicationId: 17,
					rawCitation:
						'Attention-deficit/hyperactivity disorder and occupational outcomes: The role of educational attainment, general cognitive ability, and gender. DOI: 10.1371/journal.pone.0247724',
					rawCitationWithLinks:
						'Attention-deficit/hyperactivity disorder and occupational outcomes: The role of educational attainment, general cognitive ability, and gender. DOI: 10.1371/journal.pone.0247724',
					seq: 2,
					sourceHost: 'Public Library of Science',
					sourceIssn: '1932-6203',
					sourceName: 'PLoS ONE',
					sourceType: 'journal',
					title:
						'Attention-deficit/hyperactivity disorder and occupational outcomes: The role of educational attainment, comorbid developmental disorders, and intellectual disability',
					type: 'journal-article',
					url: null,
					urn: null,
					volume: '16',
					wikidata: null,
				},
			],
		}),
		canEdit: true,
		componentForms: {
			citationStructuredEditForm: {
				id: 'citation_structured',
				method: 'PUT',
				action: 'emit',
				fields: [
					{
						name: 'rawCitation',
						component: 'field-textarea',
						label: 'Edit Raw Citation',
						description: '',
						groupId: 'default',
						isRequired: true,
						isMultilingual: false,
						isInert: false,
						value: null,
					},
					{
						name: 'doi',
						component: 'field-text',
						label: 'DOI',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'url',
						component: 'field-text',
						label: 'URL',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'urn',
						component: 'field-text',
						label: 'URN',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'arxiv',
						component: 'field-text',
						label: 'Arxiv',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'handle',
						component: 'field-text',
						label: 'Handle',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'title',
						component: 'field-text',
						label: 'Title',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'authors',
						component: 'field-authors',
						label: 'Author Information',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: [],
						addButtonLabel: '',
					},
					{
						name: 'sourceName',
						component: 'field-text',
						label: 'Source Name',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'sourceIssn',
						component: 'field-text',
						label: 'Source Issn',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'sourceHost',
						component: 'field-text',
						label: 'Publisher or Host',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'sourceType',
						component: 'field-text',
						label: 'Source Type',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'date',
						component: 'field-text',
						label: 'Publication Date',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'date',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'type',
						component: 'field-text',
						label: 'Type',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'volume',
						component: 'field-text',
						label: 'Volume',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'issue',
						component: 'field-text',
						label: 'Issue',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'pages',
						component: 'field-text',
						label: 'Pages',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'firstPage',
						component: 'field-text',
						label: 'First Page',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
					{
						name: 'lastPage',
						component: 'field-text',
						label: 'Last Page',
						description: '',
						groupId: 'default',
						isRequired: false,
						isMultilingual: false,
						isInert: false,
						value: null,
						inputType: 'text',
						optIntoEdit: false,
						optIntoEditLabel: '',
						size: 'normal',
						prefix: '',
					},
				],
				groups: [{id: 'default', pageId: 'default'}],
				hiddenFields: {},
				pages: [{id: 'default', submitButton: {label: 'Save'}}],
				primaryLocale: 'en',
				visibleLocales: ['en'],
				supportedFormLocales: [],
				errors: {},
				showErrorFooter: true,
			},
		},
	},
};
