export const UserGroupMock = {
	itemsMax: 18,
	items: [
		{
			id: 2,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Journal manager',
		},
		{
			id: 3,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Journal editor',
		},
		{
			id: 4,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Production editor',
		},
		{
			id: 5,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Section editor',
		},
		{
			id: 6,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Guest editor',
		},
		{
			id: 7,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Copyeditor',
		},
		{
			id: 8,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Designer',
		},
		{
			id: 9,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Funding coordinator',
		},
		{
			id: 10,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Indexer',
		},
		{
			id: 11,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Layout Editor',
		},
		{
			id: 12,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Marketing and sales coordinator',
		},
		{
			id: 13,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Proofreader',
		},
		{
			id: 14,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Author',
		},
		{
			id: 15,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Translator',
		},
		{
			id: 16,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Reviewer',
		},
		{
			id: 17,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Reader',
		},
		{
			id: 18,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Subscription Manager',
		},
		{
			id: 19,
			roleId: null,
			isDefault: true,
			showTitle: true,
			name: 'Editorial Board Member',
		},
	],
};
