<script>
import UsersListPanel from '@/components/ListPanel/users/UsersListPanel.vue';

export default {
	extends: UsersListPanel,
	name: 'ExampleUsersListPanel',
	data: function () {
		return {
			id: 'ExampleSubmissionsListPanel',
			searchPhrase: '',
			isLoading: false,
			isOrdering: false,
			isFilterVisible: false,
			count: 3,
			offset: 0,
			apiPath: '',
			getParams: {},
			activeFilters: {},
			filters: {
				status: {
					heading: 'Status',
					filters: [
						{
							param: 'status',
							val: 'active',
							title: 'Active',
						},
						{
							param: 'status',
							val: 'disabled',
							title: 'Disabled',
						},
					],
				},
			},
			addUserUrl: '/grid/settings/user/userGrid/addUser',
			loginAsUrl: '/login/signInAsUser/__id__',
			logoutAsUrl: '/login/signOutAsUser',
			sendEmailUrl: '/grid/settings/user/userGrid/sendEmail/__id__',
			editUserUrl: '/grid/settings/user/userGrid/editUser/__id__',
			enableUserUrl: '/grid/settings/user/userGrid/enableUser/__id__',
			disableUserUrl: '/grid/settings/user/userGrid/disableUser/__id__',
			removeUserUrl: '/grid/settings/user/userGrid/removeUser/__id__',
			mergeUserUrl: '/grid/settings/user/userGrid/mergeUser/__id__',
			items: [
				{
					'id': 5,
					'_href': 'https://localhost/api/v1/users/5',
					'userName': 'dbarnes',
					'email': 'dbarnes@mailinator.com',
					'fullName': 'Daniel Barnes',
					'orcid': '',
					'groups': [
						{
							'id': 2,
							'name': {
								'en_US': 'Journal Manager',
								'fr_CA': 'FR Journal Manager',
							},
							'abbrev': {
								'en_US': 'JM',
								'fr_CA': 'FJM',
							},
							'roleId': 16,
							'showTitle': true,
							'permitSelfRegistration': false,
							'recommendOnly': false,
						},
					],
					'disabled': false,
					'currentUserCanAdminister': false,
				},
				{
					'id': 2,
					'_href': 'https://localhost/api/v1/users/2',
					'userName': 'sbernardo',
					'email': 'sbernardo@mailinator.com',
					'fullName': 'Stephanie Bernardo',
					'orcid': 'http://orcid.org/0000-0002-1825-0097',
					'groups': [
						{
							'id': 4,
							'name': {
								'en_US': 'Section Editor',
								'fr_CA': 'FR Section Editor',
							},
							'abbrev': {
								'en_US': 'SE',
								'fr_CA': 'FSE',
							},
							'roleId': 888,
							'showTitle': false,
							'permitSelfRegistration': false,
							'recommendOnly': true,
						},
						{
							'id': 3,
							'name': {
								'en_US': 'Author',
								'fr_CA': 'FR Author',
							},
							'abbrev': {
								'en_US': 'AU',
								'fr_CA': 'FAU',
							},
							'roleId': 999,
							'showTitle': true,
							'permitSelfRegistration': true,
							'recommendOnly': false,
						},
					],
					'disabled': false,
					'currentUserCanAdminister': false,
				},
				{
					'id': 3,
					'_href': 'https://localhost/api/v1/users/3',
					'userName': 'ccorino',
					'email': 'ccorino@mailinator.com',
					'fullName': 'Carlo Corino',
					'orcid': 'http://orcid.org/0000-0002-1825-0097',
					'groups': [
						{
							'id': 3,
							'name': {
								'en_US': 'Author',
								'fr_CA': 'FR Author',
							},
							'abbrev': {
								'en_US': 'AU',
								'fr_CA': 'FAU',
							},
							'roleId': 999,
							'showTitle': true,
							'permitSelfRegistration': true,
							'recommendOnly': false,
						},
					],
					'disabled': false,
					'currentUserCanAdminister': false,
				},
				{
					'id': 4,
					'_href': 'https://localhost/api/v1/users/4',
					'userName': 'ddisabled',
					'email': 'ddisabled@mailinator.com',
					'fullName': 'Deborah Disabled',
					'orcid': 'http://orcid.org/0000-0002-1825-0097',
					'groups': [
						{
							'id': 5,
							'name': {
								'en_US': 'Copyeditor',
								'fr_CA': 'FR Copyeditor',
							},
							'abbrev': {
								'en_US': 'CE',
								'fr_CA': 'FCE',
							},
							'roleId': 999,
							'showTitle': false,
							'permitSelfRegistration': false,
							'recommendOnly': false,
						},
					],
					'disabled': true,
					'currentUserCanAdminister': false,
				},
				{
					'id': 1,
					'_href': 'https://localhost/api/v1/users/1',
					'userName': 'admin',
					'email': 'admin@mailinator.com',
					'fullName': 'Alec Smecher',
					'orcid': '',
					'groups': [
						{
							'id': 1,
							'name': {
								'en_US': 'Admin',
								'fr_CA': 'FR Admin',
							},
							'abbrev': {
								'en_US': 'AD',
								'fr_CA': 'FAD',
							},
							'roleId': 1,
							'showTitle': false,
							'permitSelfRegistration': false,
							'recommendOnly': false,
						},
					],
					'disabled': false,
					'currentUserCanAdminister': true,
				},
				{
					'id': 6,
					'_href': 'https://localhost/api/v1/users/6',
					'userName': 'mrolles',
					'email': 'mrolleslengthyemailstring@mailinator.com',
					'fullName': 'Mannie Rolles',
					'orcid': '',
					'groups': [
						{
							'id': 6,
							'name': {
								'en_US': 'Guest Editor',
								'fr_CA': 'FR Guest Editor',
							},
							'abbrev': {
								'en_US': 'GE',
								'fr_CA': 'FGE',
							},
							'roleId': 999,
							'showTitle': false,
							'permitSelfRegistration': false,
							'recommendOnly': true,
						},
						{
							'id': 10,
							'name': {
								'en_US': 'Marketing and Sales Coordinator',
								'fr_CA': 'FR Marketing and Sales Coordinator',
							},
							'abbrev': {
								'en_US': 'MS',
								'fr_CA': 'FMS',
							},
							'roleId': 555,
							'showTitle': false,
							'permitSelfRegistration': false,
							'recommendOnly': false,
						},
						{
							'id': 3,
							'name': {
								'en_US': 'Author',
								'fr_CA': 'FR Author',
							},
							'abbrev': {
								'en_US': 'AU',
								'fr_CA': 'FAU',
							},
							'roleId': 999,
							'showTitle': true,
							'permitSelfRegistration': true,
							'recommendOnly': false,
						},
						{
							'id': 7,
							'name': {
								'en_US': 'Translator',
								'fr_CA': 'FR Translator',
							},
							'abbrev': {
								'en_US': 'TR',
								'fr_CA': 'FTR',
							},
							'roleId': 999,
							'showTitle': false,
							'permitSelfRegistration': false,
							'recommendOnly': false,
						},
						{
							'id': 4,
							'name': {
								'en_US': 'Section Editor',
								'fr_CA': 'FR Section Editor',
							},
							'abbrev': {
								'en_US': 'SE',
								'fr_CA': 'FSE',
							},
							'roleId': 888,
							'showTitle': false,
							'permitSelfRegistration': false,
							'recommendOnly': true,
						},
					],
					'disabled': false,
					'currentUserCanAdminister': true,
				},
			],
			itemsMax: 10,
			i18n: {
				title: 'Users',
				search: 'Search',
				clearSearch: 'Clear search phrase',
				loadMore: 'Load more',
				loading: 'Loading',
				viewMore: 'View more details about {$name}',
				viewLess: 'Hide expanded details about {$name}',
				itemsOfTotal: '{$count} of {$total} items',
				itemCount: '{$count} items',
				filter: 'Filters',
				filterRemove: 'Clear filter: {$filterTitle}',
				addUser: 'Add User',
				disabled: 'Disabled',
				orcid: 'ORCID',
				loginAs: 'Login As',
				logoutAs: 'Logout as',
				loginAsDescription: 'You can login as {$userName}. While logged in, all actions you perform will be attributed to this user.',
				assignedGroups: 'This user is assigned to the following groups: {$groups}',
				listSeparator: ', ',
				sendEmail: 'Send Email',
				editUser: 'Edit User',
				enableUser: 'Enable',
				disableUser: 'Disable',
				removeUser: 'Remove',
				removeUserConfirmation: 'Remove this user from this journal? This action will unenroll the user from all roles within this journal.',
				confirm: 'Ok',
				cancel: 'Cancel',
				mergeUser: 'Merge User',
			},
		};
	},
};
</script>
